### ISSUE TITLE
Request.redirectTo doesn't actually redirect the request

### ISSUE THREAD

**Issue by aisola** [MasoniteFramework/core#114]
`Request.redirectTo` doesn't actually redirect the request. Additionally, if the app developer doesn't return a real response after the call, it also causes an error (traceback below).

```
ERROR:waitress:Exception when serving /home
Traceback (most recent call last):
  File "/home/acisola/workspace/test_project/bootstrap/start.py", line 49, in app
    container.resolve(located_provider.boot)
  File "/home/acisola/workspace/test_project/venv/lib/python3.4/site-packages/masonite/app.py", line 65, in resolve
    return obj(*provider_list)
  File "/home/acisola/workspace/test_project/venv/lib/python3.4/site-packages/masonite/providers/StartResponseProvider.py", line 15, in boot
    data = bytes(Response, 'utf-8')
TypeError: encoding or errors without a string argument

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/acisola/workspace/test_project/venv/lib/python3.4/site-packages/waitress/channel.py", line 338, in service
    task.service()
  File "/home/acisola/workspace/test_project/venv/lib/python3.4/site-packages/waitress/task.py", line 169, in service
    self.execute()
  File "/home/acisola/workspace/test_project/venv/lib/python3.4/site-packages/waitress/task.py", line 399, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/home/acisola/workspace/test_project/venv/lib/python3.4/site-packages/whitenoise/base.py", line 66, in __call__
    return self.application(environ, start_response)
  File "/home/acisola/workspace/test_project/bootstrap/start.py", line 51, in app
    container.make('ExceptionHandler').load_exception(e)
  File "/home/acisola/workspace/test_project/venv/lib/python3.4/site-packages/masonite/exception_handler.py", line 28, in load_exception
    self._render()
  File "/home/acisola/workspace/test_project/venv/lib/python3.4/site-packages/masonite/exception_handler.py", line 48, in _render
    'open': open
  File "/home/acisola/workspace/test_project/venv/lib/python3.4/site-packages/masonite/view.py", line 79, in render
    self.dictionary)
  File "/home/acisola/workspace/test_project/venv/lib/python3.4/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/acisola/workspace/test_project/venv/lib/python3.4/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/acisola/workspace/test_project/venv/lib/python3.4/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/acisola/workspace/test_project/venv/lib/python3.4/site-packages/masonite/snippets/exception.html", line 62, in top-level template co
de
    {% for i, line in enumerate(open(stack.filename)) %}
TypeError: Can't convert 'Undefined' object to str implicitly
```

**Comment by josephmancuso** [comment]
Is this in the view or the middleware

**Comment by aisola** [comment]
Just as a note, `Request.redirect` works as expected still. This seems to be isolated to just `Request.redirectTo`.

**Comment by josephmancuso** [comment]
Ok that makes more sense. In that back of my head I've always though that was going to be a problem. The problem I'm pretty sure is in the route provider. Before hitting a controller method I check if the request.redirect_url is set. We need to either make a more ambiguous attribute like request.redirecting is True or also check for request.redirect_route. I think the first option is better

**Comment by aisola** [comment]
Why couldn't we just compile the route just in time and set it to request.redirect_url right away?

**Comment by aisola** [comment]
I guess that would make it so that we couldn't use `.send` to pass arguments. Though the View.render doesn't follow the methods over arguments pattern either. So it would make sense to make the redirects follow the same pattern as views.

**Comment by josephmancuso** [comment]
Can you give a code example of what you mean?

**Comment by josephmancuso** [comment]
It might be due for a rewrite

**Comment by josephmancuso** [comment]
A couple of the first features created May actually all need to be rewritten lol. After looking at the container code I ripped out like 50 lines and added features at the same time lol

**Comment by aisola** [comment]
For example instead of calling `Request.redirectTo('some_update_method').send({'id': 1})`, in the view, one might call `Request.redirect_to('some_update_method', {'id': 1})`. Since we're thinking of a rewrite, it might also make sense to change it to the more pythonic snake case.

Here's what I was thinking for the changes in the Request.

```python

class Request(Extendable):
    
    # ...
    
    
    def redirect(self, route, params={}):
        self.redirect_url = self.compile_route_to_url(route, params)
        return self
    
    def redirect_to(self, route_name, params={}):
        WebRoutes = self.container.make('WebRoutes')
        
        for route in WebRoutes:
            if route.named_route = route_name:
                return self.redirect_url = self.compile_route_to_url(route, params)
        
        raise ValueError('Route named {} does not exist')
    
    def compile_route_to_url(self, route, params={}):
        """
        Compile the route url into a usable url
        Converts /url/@id into /url/1. Used for redirection
        """

        if 'http' in route:
            return route

        # Split the url into a list
        split_url = route.split('/')

        # Start beginning of the new compiled url
        compiled_url = '/'

        # Iterate over the list
        for url in split_url:
            if url:
                # if the url contains a parameter variable like @id:int
                if '@' in url:
                    url = url.replace('@', '').replace(
                        ':int', '').replace(':string', '')
                    compiled_url += str(self.param(url)) + '/'
                else:
                    compiled_url += url + '/'

        # The loop isn't perfect and may have an unwanted trailing slash
        if compiled_url.endswith('/') and not route.endswith('/'):
            compiled_url = compiled_url[:-1]

        # The loop isn't perfect and may have 2 slashes next to eachother
        if '//' in compiled_url:
            compiled_url = compiled_url.replace('//', '/')

        return compiled_url
```

**Comment by josephmancuso** [comment]
Ok since we are changing a method name let's target that PR with the develop branch

**Comment by aisola** [comment]
Sounds good.

**Comment by josephmancuso** [comment]
By the way, we added a new feature in one of the Masonite versions. I think 1.6.2 or something where you can group routes. So the ROUTES list can have a list. Something like:

```python
ROUTES = [
    get('/url', 'Controller@method'),
    group('/dashboard', [
        get('/user', 'Controller@method')
    ])
]
```

which will obviously return a list in a list like this:

```python
[
    get('/url', 'controller@method'),
    [
        get('/dashboard/user', 'Controller@method')
    ]
]
```

With that being said, looping in a method like:

```python
def redirect_to(self, route_name, params={}):
        WebRoutes = self.container.make('WebRoutes')
        
        for route in WebRoutes:
            if route.named_route = route_name:
                return self.redirect_url = self.compile_route_to_url(route, params)
```

will throw an error because `route` could be a list. Look at the top of the Route provider on how we solved it. Since it's going to be in multiple location now it will be wise to abstract that logic out into a helper method or something.

**Comment by josephmancuso** [comment]
something like:

```python
def collect_routes(web_routes):
    # Rebuild Route List
        RouteCollection = []
        for route in web_routes:
            # Check if a route is a list of routes
            if isinstance(route, list):
                for r in route:
                    RouteCollection.append(r)
            else:
                RouteCollection.append(route)
```

and then use that method in several places

**Comment by josephmancuso** [comment]
or we can just throw that way in the beginning actually where `WebRoutes` are loaded into the container and just call it a day lol

```python
from masonite.helpers import collect_routes
...

class AppProvider(ServiceProvider):

    def register(self):
        self.app.bind('HookHandler', Hook(self.app))

        # change is here
        self.app.bind('WebRoutes', collect_routes(web.ROUTES))

        self.app.bind('Response', None)
```

**Comment by aisola** [comment]
Yup, I discovered that. Working on this now.
