### ISSUE TITLE
masonite.exceptions.ContainerError raises when I remove MailProvider from Optional Framework Providers

### ISSUE THREAD

**Issue by vaibhavmule** [MasoniteFramework/core#394]
`WARNING: The dependency with the manager: masonite.managers.MailManager.MailManager annotation could not be resolved by the container`

Traceback

```
Traceback (most recent call last):
  File "/Users/vaibhavmule/.local/share/virtualenvs/github-notifications-OHJhASIP/bin/craft", line 7, in <module>
    from masonite_cli.application import application
  File "/Users/vaibhavmule/.local/share/virtualenvs/github-notifications-OHJhASIP/lib/python3.7/site-packages/masonite_cli/application.py", line 39, in <module>
    from wsgi import container
  File "/Users/vaibhavmule/Dropbox/work/github-notifications/wsgi.py", line 39, in <module>
    container.resolve(provider.boot)
  File "/Users/vaibhavmule/.local/share/virtualenvs/github-notifications-OHJhASIP/lib/python3.7/site-packages/masonite/app.py", line 136, in resolve
    provider_list.append(self._find_annotated_parameter(value))
  File "/Users/vaibhavmule/.local/share/virtualenvs/github-notifications-OHJhASIP/lib/python3.7/site-packages/masonite/app.py", line 211, in _find_annotated_parameter
    'The dependency with the {0} annotation could not be resolved by the container'.format(parameter))
masonite.exceptions.ContainerError: The dependency with the manager: masonite.managers.MailManager.MailManager annotation could not be resolved by the container
```

Masonite Version: masonite = "==2.1.0b2"

**Comment by josephmancuso** [comment]
where is it trying to resolve this?

**Comment by josephmancuso** [comment]
very strange.

```
File "/Users/vaibhavmule/Dropbox/work/github-notifications/wsgi.py", line 39, in <module>
    container.resolve(provider.boot)
```

says it's trying to resolve it in a boot method somewhere

**Comment by vaibhavmule** [comment]
I found it, it is because HelpersProvider uses MailManger. 

If I comment out HelperProider, I get no errors.

**Comment by josephmancuso** [comment]
hmm interesting. ok good to know. Maybe we will have to take it out of the boot method and find it using `self.app`

**Comment by vaibhavmule** [comment]
Shall we tag this as a bug?

**Comment by josephmancuso** [comment]
sure

**Comment by josephmancuso** [comment]
working on this now
